### ISSUE TITLE
 java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by mostfa-ayad** [hawkxu/jrviewer-fx#1]
hello  
thanks for this work
when using this in tornadofx  i face this
java.lang.NoSuchMethodError: java.lang.NoSuchMethodError: net.sf.jasperreports.export.SimpleGraphics2DReportConfiguration.setWhitePageBackground(Ljava/lang/Boolean;)V
	at win.zqxu.jrviewer.JRViewerFX.printPageToImage(JRViewerFX.java:316)
	at win.zqxu.jrviewer.JRViewerFXSkin.updatePreview(JRViewerFXSkin.java:415)
	at win.zqxu.jrviewer.JRViewerFXSkin.showPage(JRViewerFXSkin.java:320)
	at win.zqxu.jrviewer.JRViewerFXSkin.updateReport(JRViewerFXSkin.java:293)
	at win.zqxu.jrviewer.JRViewerFXSkin.<init>(JRViewerFXSkin.java:101)
	at win.zqxu.jrviewer.JRViewerFX.createDefaultSkin(JRViewerFX.java:101)

**Comment by mostfa-ayad** [comment]
hi hawkxu 
i using version 6.1.0

**Comment by hawkxu** [comment]
Hi mostfa-ayad,
Please try the new version 0.1.1 of jrviewer-fx, thanks!

**Comment by hawkxu** [comment]
closed by d461763
