### ISSUE TITLE
null poit Exception

### ISSUE THREAD

**Issue by gestshb** [hawkxu/jrviewer-fx#2]
hello
i get this error when i call
` JRViewerFX.preview(((Node) event.getSource()).getScene().getWindow(), print);`

stack...
`aused by: java.lang.NullPointerException
	at win.zqxu.jrviewer.JRViewerFXSkin.updatePrinter(JRViewerFXSkin.java:427)
	at win.zqxu.jrviewer.JRViewerFXSkin.<init>(JRViewerFXSkin.java:102)
	at win.zqxu.jrviewer.JRViewerFX.createDefaultSkin(JRViewerFX.java:101)
	at javafx.scene.control.Control.impl_processCSS(Control.java:872)
	at javafx.scene.Node.processCSS(Node.java:9058)
	at javafx.scene.Scene.doCSSPass(Scene.java:545)
	at javafx.scene.Scene.preferredSize(Scene.java:1643)
	at javafx.scene.Scene.impl_preferredSize(Scene.java:1720)
	at javafx.stage.Window$9.invalidated(Window.java:864)
	at javafx.beans.property.BooleanPropertyBase.markInvalid(BooleanPropertyBase.java:109)`

i have not any printer installed

**Comment by hawkxu** [comment]
Sorry I didn't think about that there is no any printer in system, maybe you could install a free virtual printer in your system, like a free pdf printer, thanks
